apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: instagram-prod

resources:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: production

replicas:
  - name: api-gateway
    count: 3
  - name: frontend
    count: 3
  - name: post-service
    count: 2
  - name: feed-service
    count: 2
  - name: user-service
    count: 2
  - name: auth-service
    count: 2
  - name: notification-service
    count: 2
