apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: instagram

resources:
  - namespace.yaml
  - media-storage/pvc.yaml
  - postgres/secret.yaml
  - postgres/configmap.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - redis/deployment.yaml
  - redis/service.yaml
  - kafka/zookeeper-statefulset.yaml
  - kafka/zookeeper-service.yaml
  - kafka/kafka-statefulset.yaml
  - kafka/kafka-service.yaml
  - auth-service/deployment.yaml
  - user-service/deployment.yaml
  - post-service/deployment.yaml
  - post-service/hpa.yaml
  - feed-service/deployment.yaml
  - feed-service/hpa.yaml
  - notification-service/deployment.yaml
  - api-gateway/deployment.yaml
  - api-gateway/hpa.yaml
  - frontend/deployment.yaml
  - frontend/hpa.yaml
  - nginx/ingress.yaml
