apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: instagram
data:
  init.sql: |
    CREATE DATABASE auth_db;
    CREATE DATABASE user_db;
    CREATE DATABASE post_db;
    CREATE DATABASE feed_db;
    CREATE DATABASE notification_db;

    GRANT ALL PRIVILEGES ON DATABASE auth_db TO instagram;
    GRANT ALL PRIVILEGES ON DATABASE user_db TO instagram;
    GRANT ALL PRIVILEGES ON DATABASE post_db TO instagram;
    GRANT ALL PRIVILEGES ON DATABASE feed_db TO instagram;
    GRANT ALL PRIVILEGES ON DATABASE notification_db TO instagram;
